export enum OperatorResponseStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
}
